const menuTrees = [
    {
      alwaysShow:true,
      name:'AA',
      component:'layout/index.vue',
      title:'首页',
      path:'/Main',
      redirect: '/dashboard',
    },
    {
      alwaysShow:true,
      name:'系统管理',
      component:'layout/index.vue',
      title:'系统管理',
      path:'/local_system',
      children:[
        {
          alwaysShow:true,
          name:'菜单管理',
          component:'views/system/menu/index.vue',
          title:'菜单管理',
          path:'menu',
        },
        {
          alwaysShow:true,
          name:'用户管理',
          component:'views/system/user/index.vue',
          title:'用户管理',
          path:'user',
        }
      ]
    },
    {
      alwaysShow:true,
      name:'WebGIS模块',
      component:'layout/index.vue',
      title:'WebGIS模块',
      path:'/webgis',
      children:[
        {
          alwaysShow:true,
          name:'cesium',
          component:'views/webgis/cesium/index.vue',
          title:'cesium',
          path:'cesium',
        },
        {
          alwaysShow:true,
          name:'leaflet',
          component:'views/webgis/leaflet/index.vue',
          title:'leaflet',
          path:'leaflet',
        },
        {
          alwaysShow:true,
          name:'测试',
          component:'views/MyText.vue',
          title:'测试',
          path:'text',
        }
      ]
    },
    {
      alwaysShow:true,
      name:'实用工具',
      component:'layout/index.vue',
      title:'实用工具',
      path:'/tools',
      children:[
        {
          alwaysShow:true,
          name:'practise',
          component:'views/usefultools/practise/index.vue',
          title:'practise',
          path:'practise',
        },
        {
          alwaysShow:true,
          name:'time',
          component:'views/usefultools/time/index.vue',
          title:'time',
          path:'time',
        },
      ]
    },
  ]

  export default menuTrees