const menuTrees = [
    {
      alwaysShow:true,
      name:'首页',
      component:'layout/index.vue',
      title:'首页',
      path:'/te',
    },
    {
      alwaysShow:true,
      name:'一级菜单一',
      component:'layout/index.vue',
      title:'一级菜单一',
      path:'/ta',
      children:[
        {
          alwaysShow:true,
          name:'二级菜单一',
          component:'views/MyText.vue',
          title:'二级菜单一',
          path:'/text',
        },
        {
          alwaysShow:true,
          name:'二级菜单二',
          component:'views/MyText.vue',
          title:'二级菜单二',
          path:'/text',
        }
      ]
    },
    {
      alwaysShow:true,
      name:'一级菜单二',
      component:'layout/index.vue',
      title:'一级菜单二',
      path:'/text2',
      children:[
        {
          alwaysShow:true,
          name:'二级菜单一2',
          component:'views/MyText.vue',
          title:'二级菜单一',
          path:'/text',
        },
        {
          alwaysShow:true,
          name:'二级菜单二2',
          component:'views/MyText.vue',
          title:'二级菜单二',
          path:'/text',
        },
        {
          alwaysShow:true,
          name:'二级菜单三2',
          component:'views/MyText.vue',
          title:'二级菜单三',
          path:'/text',
        }
      ]
    }
  ]

  export default menuTrees