const menuTrees = [
    {
      alwaysShow:true,
      component:'views/MyText.vue',
      title:'首页',
      path:'/text1',
    },
    {
      alwaysShow:true,
      component:'views/MyText.vue',
      title:'一级菜单一',
      path:'/text1',
      children:[
        {
          alwaysShow:true,
          component:'views/MyText.vue',
          title:'二级菜单一',
          path:'/text',
        },
        {
          alwaysShow:true,
          component:'views/MyText.vue',
          title:'二级菜单二',
          path:'/text',
        }
      ]
    },
    {
      alwaysShow:true,
      component:'views/MyText.vue',
      title:'一级菜单二',
      path:'/text2',
      children:[
        {
          alwaysShow:true,
          component:'views/MyText.vue',
          title:'二级菜单一',
          path:'/text',
        },
        {
          alwaysShow:true,
          component:'views/MyText.vue',
          title:'二级菜单二',
          path:'/text',
        },
        {
          alwaysShow:true,
          component:'views/MyText.vue',
          title:'二级菜单三',
          path:'/text',
        }
      ]
    }
  ]

  export default menuTrees